### ISSUE TITLE
eda is unable to recognize file names

### ISSUE THREAD

**Issue by jehart15** [jschnab/easy-data-analysis#9]
jaynees-mbp:desktop jayneehart$ eda plot spectrum LOV1+2-DKdil-25Feb20.csv
Error: FileNotFoundError [Errno 2] No such file or directory: '/Users/jayneehart/.edaconf'

**Comment by jschnab** [comment]
I see what's the problem, I'll fix this soon. In the meantime you can go around this by running `eda configure default` to generate the file `.edaconf`.
